### ISSUE TITLE
HealthCondition is importing HealthKit (causing app rejection)

### ISSUE THREAD

**Issue by ericallam** [pluralsight/PSOperations#34]
I recently submitted to app review for the first time after incorporating PSOperations into my project and was rejected because of HealthCondition. I wasn't using it, but it does import HealthKit and it was included in my target. The app review team didn't like that (the app I submitted is a game and not related to health at all) and so I was rejected because of:

"Apps using the HealthKit framework must indicate integration with the Health app in their marketing text and must clearly identify the HealthKit functionality in the app's user interface"

This seems likely to happen to other people using PSOperations.

**Comment by MarkQSchultz** [comment]
We've seen a similar issue with wallet. Our app is marked as supporting wallet, even though we don't use it at all.

**Comment by mcmurrym** [comment]
Hmmm I think the true fix is that Apple shouldn't assume you are using an Apple feature just because you import a framework. The capabilities list under your app target are what should be used to determine what your app uses... I would double check your capabilities list and make sure Health isn't enabled?

**Comment by fernandomorgan** [comment]
Also had that rejection at first, but app was approved after email response. Even so, might be better to remove those if you aren't using it

**Comment by andresbrun** [comment]
Is there any chance to solve this issue (by merging the proposed PR for instance)? I've run into the same problem. I have been chatting with App Store review team but the proposed solution is either remove PSOperations or to talk with their owners to remove HealthKit.framework. 

Thanks in advance

**Comment by gblotter** [comment]
@MarkQSchultz and @mcmurrym - Hey Guys 😊 Just tried to get The VOID's new app approved through Apple, and ran into the same problem.  Do we know what the current work around it?

**Comment by mcmurrym** [comment]
Let’s put the wallet and the health ones separate repos for now. I’ll work on this tomorrow morning.

**Comment by mcmurrym** [comment]
Sorry for the delay. I'll have a pull request up later today that keeps these in the same repo, but not included in the target/framework. You will be able to add them to your own project/target(s) if you need them.

**Comment by mcmurrym** [comment]
See #64

**Comment by mcmurrym** [comment]
#64 merged, this issue should be resolved.

**Comment by automactic** [comment]
@mcmurrym No, this issue still exist. However, I was able to remove the health kit and wallet related file by using `pod 'PSOperations/Core', '~> 2.3'`. Will you consider modifying readme.md, so others won't have their app rejected?

**Comment by mcmurrym** [comment]
k, so it is fixed, just needs a readme update, there is already a pull request for it. Glad you got it worked out.

**Comment by andresbrun** [comment]
Just an quick note: this works for Cocoapods but as far as I know is still an issue if you use Carthage.
